# Generated by Django 2.1.5 on 2019-01-16 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attended',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(max_length=222)),
                ('start', models.DateTimeField(max_length=6)),
                ('end', models.DateTimeField(max_length=222)),
                ('status', models.CharField(max_length=226)),
                ('created_at', models.DateTimeField(max_length=6)),
                ('updated_at', models.DateTimeField(max_length=6)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(max_length=6),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(max_length=6),
        ),
    ]
